import React, { useRef, useState, useEffect } from 'react';
import {
    View,
    ScrollView,
    FlatList,
    TouchableOpacity,
    Linking,
    Animated,
    Dimensions,
    ActivityIndicator,
} from 'react-native';
import { Text } from '../../components/Text';
import { useUser } from '@clerk/clerk-expo';
import { dataService } from '../../api/dataService';

const { width } = Dimensions.get('window');

const AnnouncementCarousel = ({ data }: { data: any[] }) => {
    const [current, setCurrent] = useState(0);
    const fadeAnim = useRef(new Animated.Value(1)).current;

    useEffect(() => {
        if (!data || data.length === 0) return;
        const interval = setInterval(() => {
            Animated.sequence([
                Animated.timing(fadeAnim, { toValue: 0, duration: 300, useNativeDriver: true }),
                Animated.timing(fadeAnim, { toValue: 1, duration: 300, useNativeDriver: true }),
            ]).start();
            setCurrent(c => (c + 1) % data.length);
        }, 4000);
        return () => clearInterval(interval);
    }, [data, fadeAnim]);

    if (!data || data.length === 0) return null;

    const item = data[current];

    return (
        <Animated.View style={{ opacity: fadeAnim }} className="mx-4 mb-4 overflow-hidden rounded-xl">
            {item.image ? (
                <View className="relative h-40">
                    <Animated.Image source={{ uri: item.image }} className="w-full h-full" resizeMode="cover" />
                    <View className="absolute inset-0 bg-black/40 p-4 justify-end">
                        <Text variant="caption" className="text-white/80 mb-1">ANNOUNCEMENT</Text>
                        <Text variant="h3" className="text-white mb-1 font-bold" numberOfLines={1}>{item.title}</Text>
                        <Text variant="caption" className="text-white/90" numberOfLines={2}>{item.body}</Text>
                    </View>
                </View>
            ) : (
                <View className="bg-blue-600 p-4">
                    <Text variant="caption" className="text-blue-200 mb-1">ANNOUNCEMENT</Text>
                    <Text variant="h3" className="text-white mb-1 font-bold" numberOfLines={1}>{item.title}</Text>
                    <Text variant="caption" className="text-blue-100" numberOfLines={2}>{item.body}</Text>
                </View>
            )}
            <View className="flex-row absolute bottom-3 left-4">
                {data.map((_, i) => (
                    <View key={i} className={`h-1.5 rounded-full mr-1 ${i === current ? 'bg-white w-4' : 'bg-white/40 w-1.5'}`} />
                ))}
            </View>
        </Animated.View>
    );
};

const CourseCard = ({ item }: { item: any }) => (
    <TouchableOpacity
        style={{ backgroundColor: '#2563EB' }}
        className="rounded-xl overflow-hidden mr-3 w-44 shadow-lg shadow-blue-600/20"
        activeOpacity={0.85}
    >
        {item.image ? (
            <View className="h-28">
                <Animated.Image source={{ uri: item.image }} className="w-full h-full" resizeMode="cover" />
            </View>
        ) : (
            <View className="h-28 bg-blue-700 items-center justify-center">
                <Text style={{ fontSize: 40 }}>📚</Text>
            </View>
        )}
        <View className="p-3">
            <Text variant="body" className="text-white font-bold mb-1" numberOfLines={1}>{item.title}</Text>
            <Text variant="caption" className="text-blue-100" numberOfLines={1}>
                {item.lessons?.length || 0} Videos
            </Text>
            <View className="mt-3 bg-white/20 rounded-lg py-1.5 items-center">
                <Text className="text-white text-[10px] font-bold tracking-wider uppercase">View Playlist</Text>
            </View>
        </View>
    </TouchableOpacity>
);

import { useAuth } from '@clerk/clerk-expo';
import { ComingSoon } from '../../components/ComingSoon';
import { Video } from 'lucide-react-native';

export const HomeScreen = ({ navigation }: any) => {
    const { user } = useUser();
    const { isLoaded, isSignedIn } = useAuth();
    const [dashboardData, setDashboardData] = useState<any>(null);
    const [announcements, setAnnouncements] = useState<any[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const fetchDashboardData = async () => {
            if (!isLoaded || !isSignedIn) return; // Wait until token is explicitly generated by Clerk
            setIsLoading(true);
            try {
                const [dashboardRes, announcementsRes] = await Promise.all([
                    dataService.getDashboard(),
                    dataService.getAnnouncements()
                ]);
                setDashboardData(dashboardRes);
                setAnnouncements(announcementsRes);
            } catch (error) {
                console.error('Error fetching dashboard data:', error);
            } finally {
                setIsLoading(false);
            }
        };
        fetchDashboardData();
    }, [isLoaded, isSignedIn]);

    if (isLoading) {
        return (
            <View className="flex-1 items-center justify-center bg-white dark:bg-gray-900">
                <ActivityIndicator size="large" color="#2563EB" />
            </View>
        );
    }

    const displayName = user?.firstName ? `${user.firstName} ${user.lastName || ''}`.trim() : 'Student';

    return (
        <ScrollView className="flex-1 bg-gray-50 dark:bg-gray-900" showsVerticalScrollIndicator={false}>

            {/* Header */}
            <View className="bg-blue-600 pt-14 pb-8 px-4 rounded-b-3xl mb-4">
                <Text variant="caption" className="text-blue-200 mb-1">Hello 👋</Text>
                <Text variant="h2" className="text-white font-bold">{displayName}</Text>
                <Text variant="caption" className="text-blue-200 mt-0.5">Keep pushing your preparation!</Text>
            </View>

            <AnnouncementCarousel data={announcements} />

            {/* Stats Row */}
            <View className="flex-row px-4 justify-between mb-6">
                <View className="bg-white dark:bg-gray-800 p-4 rounded-2xl shadow-sm items-center w-[48%]">
                    <Text variant="h2" className="font-bold text-blue-600">{dashboardData?.stats?.courses || 0}</Text>
                    <Text variant="caption" className="text-gray-500">Total Courses</Text>
                </View>
                <View className="bg-white dark:bg-gray-800 p-4 rounded-2xl shadow-sm items-center w-[48%]">
                    <Text variant="h2" className="font-bold text-purple-600">{dashboardData?.stats?.enrolled || 0}</Text>
                    <Text variant="caption" className="text-gray-500">Enrolled</Text>
                </View>
            </View>

            {/* Video Playlists (Courses) */}
            <Text variant="h3" className="font-bold px-4 mb-3 text-gray-800 dark:text-white">✨ Video Playlists</Text>
            {dashboardData?.newestCourses?.length > 0 ? (
                <FlatList
                    data={dashboardData.newestCourses}
                    keyExtractor={i => i._id}
                    renderItem={({ item }) => <CourseCard item={item} />}
                    horizontal
                    showsHorizontalScrollIndicator={false}
                    contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 8 }}
                    className="mb-4"
                />
            ) : (
                <View className="px-4 mb-6">
                    <View className="bg-white dark:bg-gray-800 rounded-3xl overflow-hidden border border-gray-100 dark:border-gray-800 shadow-sm">
                        <ComingSoon
                            small
                            title="Coming Soon"
                            message="We're curating new video playlists just for you!"
                            icon={<Video size={32} color="#2563EB" />}
                        />
                    </View>
                </View>
            )}

            {/* Quick Access Tiles */}
            <Text variant="h3" className="font-bold px-4 mb-3 text-gray-800 dark:text-white">🚀 Quick Access</Text>
            <View className="flex-row flex-wrap px-4 gap-3 mb-4">
                {[
                    { icon: '📚', label: 'Courses', bg: 'bg-green-100', target: 'Courses' },
                    { icon: '📝', label: 'Quizzes', bg: 'bg-orange-100', target: 'Tests' },
                    { icon: '👤', label: 'Profile', bg: 'bg-pink-100', target: 'Profile' },
                ].map(tile => (
                    <TouchableOpacity
                        key={tile.label}
                        className={`${tile.bg} rounded-2xl items-center justify-center p-4`}
                        style={{ width: (width - 48) / 2 }}
                        onPress={() => navigation?.navigate(tile.target)}
                    >
                        <Text style={{ fontSize: 28 }}>{tile.icon}</Text>
                        <Text variant="caption" className="font-semibold mt-1 text-gray-700">{tile.label}</Text>
                    </TouchableOpacity>
                ))}
            </View>

            {/* Community Buttons */}
            <Text variant="h3" className="font-bold px-4 mb-3 text-gray-800 dark:text-white">📲 Join Community</Text>
            <View className="flex-row px-4 gap-3 mb-8">
                <TouchableOpacity
                    className="flex-1 bg-green-500 rounded-xl py-3.5 items-center flex-row justify-center gap-2"
                    onPress={() => Linking.openURL('https://whatsapp.com')}
                >
                    <Text className="text-white font-bold text-base">💬 WhatsApp</Text>
                </TouchableOpacity>
                <TouchableOpacity
                    className="flex-1 bg-sky-500 rounded-xl py-3.5 items-center flex-row justify-center gap-2"
                    onPress={() => Linking.openURL('https://t.me/')}
                >
                    <Text className="text-white font-bold text-base">✈️ Telegram</Text>
                </TouchableOpacity>
            </View>

        </ScrollView>
    );
};
